var credits = [

{
                "scheme": 2,
                "product": "Credit Acum",
                "rate_p": 29.0,
                "currency": "MDL",
                "commission_exam": 0,
                "commission_accord_p": 0,
                "commission_accord_min": 0,
                "commission_usage_p": 0,
                "commission_administration_m_p": 0,
                "interval_free": 0,
                "interval_passive": 0,
                "month_free_mandatory_p": "",
                "duration_min_m": 1,
                "duration_max_m": 24,
                "duration_list": 0,
                "sum_max": 20000,
                "sum_min": 5000,
                "sum_step": 1000,
                "pay_day_min": 2,
                "pay_day_max": 27
            },

           
           {
                "scheme": 2,
                "product": "Credit Prima Casă",
                "rate_p": 11.37,
                "currency": "MDL",
                "commission_exam": 0,
                "commission_accord_p": 1,
                "commission_accord_min": 0,
                "commission_usage_p": 0,
                "commission_administration_m_p": 0,
                "interval_free": 0,
                "interval_passive": 0,
                "month_free_mandatory_p": "",
                "duration_min_m": 1,
                "duration_max_m": 120,
                "duration_list": 0,
                "sum_max": 850000,
                "sum_min": 100000,
                "sum_step": 1,
                "pay_day_min": 2,
                "pay_day_max": 27
            },
           {
                "scheme": 2,
                "product": "Credit de nevoi personale fără gaj",
                "rate_p": 15.9,
                "currency": "MDL",
                "commission_exam": 0,
                "commission_accord_p": 0,
                "commission_accord_min": 0,
                "commission_usage_p": 0,
                "commission_administration_m_p": 0,
                "interval_free": 0,
                "interval_passive": 0,
                "month_free_mandatory_p": "",
                "duration_min_m": 1,
                "duration_max_m": 60,
                "duration_list": 0,
                "sum_max": 400000,
                "sum_min": 5000,
                "sum_step": 1000,
                "pay_day_min": 2,
                "pay_day_max": 27
            },

     
             {
                "scheme": 2,
                "product": "Credit de nevoi personale fără gaj (preferenţial) ",
                "rate_p": 14.9,
                "currency": "MDL",
                "commission_exam": 0,
                "commission_accord_p": 0,
                "commission_accord_min": 0,
                "commission_usage_p": 0,
                "commission_administration_m_p": 0,
                "interval_free": 0,
                "interval_passive": 0,
                "month_free_mandatory_p": "",
                "duration_min_m": 1,
                "duration_max_m": 60,
                "duration_list": 0,
                "sum_max": 400000,
                "sum_min": 5000,
                "sum_step": 1000,
                "pay_day_min": 2,
                "pay_day_max": 27
            },

   

 {
                "scheme": 2,
                "product": "Credit de nevoi personale cu gaj",
                "rate_p": 17.5,
                "currency": "MDL",
                "commission_exam": 0,
                "commission_accord_p": 0,
                "commission_accord_min": 0,
                "commission_usage_p": 0,
                "commission_administration_m_p": 0.20,
                "interval_free": 0,
                "interval_passive": 0,
                "month_free_mandatory_p": "",
                "duration_min_m": 13,
                "duration_max_m": 60,
                "duration_list": 0,
                "sum_max": 2500000,
                "sum_min": 51000,
                "sum_step": 1,
                "pay_day_min": 2,
                "pay_day_max": 27
            },

 {
                "scheme": 2,
                "product": "Credit de nevoi personale cu gaj (preferenţial)",
                "rate_p": 17.0,
                "currency": "MDL",
                "commission_exam": 0,
                "commission_accord_p": 0,
                "commission_accord_min": 0,
                "commission_usage_p": 0,
                "commission_administration_m_p": 0.20,
                "interval_free": 0,
                "interval_passive": 0,
                "month_free_mandatory_p": "",
                "duration_min_m": 13,
                "duration_max_m": 60,
                "duration_list": 0,
                "sum_max": 2500000,
                "sum_min": 51000,
                "sum_step": 1,
                "pay_day_min": 2,
                "pay_day_max": 27
            },

{
                "scheme": 2,
                "product": "Credit IMOBILIAR de achiziție",
                "rate_p": 13.5,
                "currency": "MDL",
                "commission_exam": 0,
                "commission_accord_p": 0,
                "commission_accord_min": 0,
                "commission_usage_p": 0,
                "commission_administration_m_p": 0,
                "interval_free": 0,
                "interval_passive": 0,
                "month_free_mandatory_p": "",
                "duration_min_m": 1,
                "duration_max_m": 240,
                "duration_list": 0,
                "sum_max": 2500000,
                "sum_min": 51000,
                "sum_step": 1,
                "pay_day_min": 2,
                "pay_day_max": 27
            },

{
                "scheme": 2,
                "product": "Credit IMOBILIAR de achiziție (preferenţial)",
                "rate_p": 13,
                "currency": "MDL",
                "commission_exam": 0,
                "commission_accord_p": 0,
                "commission_accord_min": 0,
                "commission_usage_p": 0,
                "commission_administration_m_p": 0,
                "interval_free": 0,
                "interval_passive": 0,
                "month_free_mandatory_p": "",
                "duration_min_m": 1,
                "duration_max_m": 360,
                "duration_list": 0,
                "sum_max": 2500000,
                "sum_min": 10000,
                "sum_step": 1,
                "pay_day_min": 2,
                "pay_day_max": 27
            },

            {
                "scheme": 3,
                "product": "Overdraft pe card salarial Basic",
                "rate_p": 17.0,
                "currency": "MDL",
                "commission_exam": 0,
                "commission_accord_p": 1,
                "commission_accord_min": 0,
                "commission_usage_p": 0,
                "commission_administration_m_p": 0,
                "interval_free": 0,
                "interval_passive": 20,
                "month_free_mandatory_p": "",
                "duration_min_m": 21,
                "duration_max_m": 30,
                "duration_list": 0,
                "sum_max": 200000,
                "sum_min": 1,
                "sum_step": 1,
                "pay_day_min": 10,
                "pay_day_max": 15
            },

            {
                "scheme": 3,
                "product": "Overdraft pe card salarial Silver",
                "rate_p": 16.0,
                "currency": "MDL",
                "commission_exam": 0,
                "commission_accord_p": 1,
                "commission_accord_min": 0,
                "commission_usage_p": 0,
                "commission_administration_m_p": 0,
                "interval_free": 0,
                "interval_passive": 20,
                "month_free_mandatory_p": "",
                "duration_min_m": 21,
                "duration_max_m": 30,
                "duration_list": 0,
                "sum_max": 200000,
                "sum_min": 1,
                "sum_step": 1,
                "pay_day_min": 10,
                "pay_day_max": 15
            },

            {
                "scheme": 3,
                "product": "Overdraft pe card salarial GOLD",
                "rate_p": 15.0,
                "currency": "MDL",
                "commission_exam": 0,
                "commission_accord_p": 1,
                "commission_accord_min": 0,
                "commission_usage_p": 0,
                "commission_administration_m_p": 0,
                "interval_free": 0,
                "interval_passive": 20,
                "month_free_mandatory_p": "",
                "duration_min_m": 21,
                "duration_max_m": 30,
                "duration_list": 0,
                "sum_max": 200000,
                "sum_min": 1,
                "sum_step": 1,
                "pay_day_min": 10,
                "pay_day_max": 15
            },

            {
                "scheme": 3,
                "product": "Card de credit Basic",
                "rate_p": 16,
                "currency": "MDL",
                "commission_exam": 0,
                "commission_accord_p": 0,
                "commission_accord_min": 0,
                "commission_usage_p": 2,
                "commission_administration_m_p": 0,
                "interval_free": 30,
                "interval_passive": 20,
                "month_free_mandatory_p": 5,
                "duration_min_m": 1,
                "duration_max_m": 60,
                "duration_list": 0,
                "sum_max": 200000,
                "sum_min": 5000,
                "sum_step": 1000,
                "pay_day_min": 10,
                "pay_day_max": 15
            },

            {
                "scheme": 3,
                "product": "Card de credit Silver",
                "rate_p": 15.5,
                "currency": "MDL",
                "commission_exam": 0,
                "commission_accord_p": 0,
                "commission_accord_min": 0,
                "commission_usage_p": 2,
                "commission_administration_m_p": 0,
                "interval_free": 45,
                "interval_passive": 20,
                "month_free_mandatory_p": 5,
                "duration_min_m": 1,
                "duration_max_m": 60,
                "duration_list": 0,
                "sum_max": 200000,
                "sum_min": 5000,
                "sum_step": 1000,
                "pay_day_min": 10,
                "pay_day_max": 15
            },

            {
                "scheme": 3,
                "product": "Card de credit GOLD",
                "rate_p": 14.5,
                "currency": "MDL",
                "commission_exam": 0,
                "commission_accord_p": 0,
                "commission_accord_min": 0,
                "commission_usage_p": 2,
                "commission_administration_m_p": 0,
                "interval_free": 60,
                "interval_passive": 20,
                "month_free_mandatory_p": 5,
                "duration_min_m": 1,
                "duration_max_m": 60,
                "duration_list": 0,
                "sum_max": 200000,
                "sum_min": 5000,
                "sum_step": 1000,
                "pay_day_min": 10,
                "pay_day_max": 15
            },




            {
                "scheme": 3,
                "product": "Card de credit Basic (preferenţial)",
                "rate_p": 15.5,
                "currency": "MDL",
                "commission_exam": 0,
                "commission_accord_p": 0,
                "commission_accord_min": 0,
                "commission_usage_p": 1.9,
                "commission_administration_m_p": 0,
                "interval_free": 30,
                "interval_passive": 20,
                "month_free_mandatory_p": 5,
                "duration_min_m": 1,
                "duration_max_m": 60,
                "duration_list": 0,
                "sum_max": 200000,
                "sum_min": 5000,
                "sum_step": 1000,
                "pay_day_min": 10,
                "pay_day_max": 15
            },

            {
                "scheme": 3,
                "product": "Card de credit Silver (preferenţial)",
                "rate_p": 15,
                "currency": "MDL",
                "commission_exam": 0,
                "commission_accord_p": 0,
                "commission_accord_min": 0,
                "commission_usage_p": 1.9,
                "commission_administration_m_p": 0,
                "interval_free": 45,
                "interval_passive": 20,
                "month_free_mandatory_p": 5,
                "duration_min_m": 1,
                "duration_max_m": 60,
                "duration_list": 0,
                "sum_max": 200000,
                "sum_min": 5000,
                "sum_step": 1000,
                "pay_day_min": 10,
                "pay_day_max": 15
            },


            {
                "scheme": 3,
                "product": "Card de credit GOLD (preferenţial)",
                "rate_p": 14,
                "currency": "MDL",
                "commission_exam": 0,
                "commission_accord_p": 0,
                "commission_accord_min": 0,
                "commission_usage_p": 1.9,
                "commission_administration_m_p": 0,
                "interval_free": 60,
                "interval_passive": 20,
                "month_free_mandatory_p": 5,
                "duration_min_m": 1,
                "duration_max_m": 60,
                "duration_list": 0,
                "sum_max": 200000,
                "sum_min": 5000,
                "sum_step": 1000,
                "pay_day_min": 10,
                "pay_day_max": 15
            },

           
           
            {
                "scheme": 1,
                "product": "SmartCredit Basic",
                "rate_p": 0,
                "currency": "MDL",
                "commission_exam": 0,
                "commission_accord_p": 1,
                "commission_accord_min": 0,
                "commission_usage_p": 0,
                "commission_administration_m_p": 0.65,
                "interval_free": 0,
                "interval_passive": 0,
                "month_free_mandatory_p": "",
                "duration_min_m": 12,
                "duration_max_m": 24,
                "duration_list": "12,24",
                "sum_max": 200000,
                "sum_min": 5000,
                "sum_step": 1,
                "pay_day_min": 2,
                "pay_day_max": 27
            },


            {
                "scheme": 1,
                "product": "SmartCredit GOLD",
                "rate_p": 0,
                "currency": "MDL",
                "commission_exam": 0,
                "commission_accord_p": 0,
                "commission_accord_min": 0,
                "commission_usage_p": 0,
                "commission_administration_m_p": 0,
                "interval_free": 0,
                "interval_passive": 0,
                "month_free_mandatory_p": "",
                "duration_min_m": 12,
                "duration_max_m": 24,
                "duration_list": "12,24",
                "sum_max": 200000,
                "sum_min": 5000,
                "sum_step": 1,
                "pay_day_min": 2,
                "pay_day_max": 27
            },

           
        ];